# Generated by Django 3.0 on 2021-08-04 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBlog', models.CharField(db_index=True, max_length=400, unique=True, verbose_name='Название блога')),
                ('textBlog', models.TextField(max_length=500000, unique=True, verbose_name='Текст блога')),
                ('showBlog', models.BooleanField(default=False, verbose_name='Показать нужный нужный блог')),
            ],
            options={
                'verbose_name': 'Блоги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст комментарий')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comment.Comments', verbose_name='Родительская и дочерняя связь')),
            ],
            options={
                'verbose_name': 'Комментарии пользователей',
                'ordering': ['id'],
            },
        ),
    ]
