# Generated by Django 3.0 on 2021-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='textBlog',
            field=models.TextField(max_length=1000000000, unique=True, verbose_name='Текст блога'),
        ),
    ]
